# BARE BONES CloudCannon Configuration - Testing Only

# Build Configuration with timeout
build:
  command: npm run build
  output: dist/
  environment:
    - NODE_ENV=production
  timeout: 600  # 10 minutes timeout

# Source Configuration (root level)
source:
  path: ./

# Simplified Collections
collections_config:
  pages:
    path: src/pages/
    name: Pages

# Basic Paths
paths:
  static: public
  uploads: public

# Prevent watch mode issues
dev:
  command: npm run dev
  output: dist/
  
# Additional settings to prevent loops
editor:
  default_path: /
  
# Disable auto-reload during build
data_config:
  timezone: UTC 